brew 'chruby'
brew 'curl'
brew 'node'
brew 'openssl'
brew 'python'
brew 'python3'
brew 'ruby-install'
brew 'tmux'
brew 'vim'
brew 'wget'
brew 'zsh'

tap 'caskroom/cask'
cask_args appdir: '/Applications'
cask 'firefox'
cask 'google-chrome'
cask 'openemu'
cask 'transmission'

tap 'caskroom/homebrew-fonts'
cask 'font-bitstream-vera'
cask 'font-hack'
cask 'font-inconsolata'
cask 'font-roboto'

# MAS: 1password, tweetbot, dash, xscope, reeder
