cask_args appdir: "/Applications"

tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/services"

brew "chruby"
brew "ctop"
brew "git"
brew "go"
brew "httpie"
brew "hub"
brew "jq"
brew "mas"
brew "neovim"
brew "node"
brew "openssl"
brew "postgresql"
brew "python"
brew "python@2"
brew "ranger"
brew "reattach-to-user-namespace"
brew "redis"
brew "ruby-install"
brew "terraform"
brew "tmux"
brew "vault"
brew "yarn"
brew "zsh"

cask "google-cloud-sdk"
cask "font-hack"
cask "font-open-sans"
cask "highsierramediakeyenabler"

# mas "Calcbot", id: 931657367
# mas "Pastebot", id: 1179623856
# mas "Reeder", id: 880001334
# mas "Tweetbot", id: 557168941
# mas "Tweetbot", id: 1384080005
